# which benchmarks to run
benchmarks = '../test/ssa_roundtrip/*.bril'
# how to extract the performance metric from stderr
extract = 'total_dyn_inst: (\d+)'

[runs.baseline]
pipeline = [
  "bril2json",
  "brili -p {args}",
]

[runs.ssa_baseline]
pipeline = [
  "bril2json",
  "python3 ../tdce.py tdce+",
  "python3 ../to_ssa.py",
  "python3 ../tdce.py tdce+",
  "python3 ../from_ssa.py",
  "python3 ../tdce.py tdce+",
  "brili -p {args}",
]

[runs.ssa]
pipeline = [
  "bril2json",
  "python3 ../tdce.py tdce+",
  "python3 ssa.py",
  "python3 ../tdce.py tdce+",
  "brili -p {args}",
]